theme: minima
title: Resume
author: Louis Chinenye Njoku
description: A cloud/Devops engineer, AWS certified cloud practioner and AWS solutions architect associate with experience in automation of infracture and architectorial design. 
